var strings = {
  de: {
    language: 'Sprache',
    language_de: 'Deutsch',
    language_en: 'Englisch',
    language_fr: 'Französisch',
    language_it: 'Italienisch',
    language_es: 'Spanisch',
    button: 'Mixen',
    donate: 'Spendier mir einen Kaffee',
  },
  en: {
    language: 'Language',
    language_de: 'German',
    language_en: 'English',
    language_fr: 'French',
    language_it: 'Italian',
    language_es: 'Spanish',
    button: 'Mix',
    donate: 'Donate me a coffee',
  },
  fr: {
    language: 'Langue',
    language_de: 'Allemand',
    language_en: 'Anglais',
    language_fr: 'Français',
    language_it: 'Italien',
    language_es: 'Espagnol',
    button: 'Mélanger',
    donate: 'Donnez-moi un café',
  },
  it: {
    language: 'Lingua',
    language_de: 'Tedesco',
    language_en: 'Inglese',
    language_fr: 'Francese',
    language_it: 'Italiano',
    language_es: 'Spagnolo',
    button: 'Mescola',
    donate: 'Dona un caffè a me',
  },
  es: {
    language: 'Idioma',
    language_de: 'Alemán',
    language_en: 'Inglés',
    language_fr: 'Francés',
    language_it: 'Italiano',
    language_es: 'Español',
    button: 'Mezclar',
    donate: 'Doname un café',
  }
}